#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2019.3.7f1_6437fd74d35d"
#define UNITY_VERSION_FULL_NICE "2019.3.7f1 (6437fd74d35d)"
#define UNITY_VERSION_BLD 6567933
#define UNITY_VERSION_DATE 1584692582
#define UNITY_VERSION_WIN "2019.3.7.6567933"
#define UNITY_VERSION_BRANCH "2019.3/staging"
